# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6302, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# coding: utf-8

from setuptools import setup, find_packages

NAME = "azurecommunicationservices"
VERSION = "0.1.0"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["msrest>=0.6.0", "azure-core<2.0.0,>=1.2.0"]

setup(
    name=NAME,
    version=VERSION,
    description="AzureCommunicationServices",
    author_email="",
    url="",
    keywords=["Swagger", "AzureCommunicationServices"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Azure Communication SMS Service.
    """
)
