# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import ADGroup
    from ._models_py3 import AddOwnerParameters
    from ._models_py3 import AppRole
    from ._models_py3 import Application
    from ._models_py3 import ApplicationBase
    from ._models_py3 import ApplicationCreateParameters
    from ._models_py3 import ApplicationListResult
    from ._models_py3 import ApplicationUpdateParameters
    from ._models_py3 import CheckGroupMembershipParameters
    from ._models_py3 import CheckGroupMembershipResult
    from ._models_py3 import DirectoryObject
    from ._models_py3 import DirectoryObjectListResult
    from ._models_py3 import Domain
    from ._models_py3 import DomainListResult
    from ._models_py3 import GetObjectsParameters
    from ._models_py3 import GraphError
    from ._models_py3 import GroupAddMemberParameters
    from ._models_py3 import GroupCreateParameters
    from ._models_py3 import GroupGetMemberGroupsParameters
    from ._models_py3 import GroupGetMemberGroupsResult
    from ._models_py3 import GroupListResult
    from ._models_py3 import InformationalUrl
    from ._models_py3 import KeyCredential
    from ._models_py3 import KeyCredentialListResult
    from ._models_py3 import KeyCredentialsUpdateParameters
    from ._models_py3 import OAuth2Permission
    from ._models_py3 import OAuth2PermissionGrant
    from ._models_py3 import OAuth2PermissionGrantListResult
    from ._models_py3 import OptionalClaim
    from ._models_py3 import OptionalClaims
    from ._models_py3 import PasswordCredential
    from ._models_py3 import PasswordCredentialListResult
    from ._models_py3 import PasswordCredentialsUpdateParameters
    from ._models_py3 import PasswordProfile
    from ._models_py3 import PreAuthorizedApplication
    from ._models_py3 import PreAuthorizedApplicationExtension
    from ._models_py3 import PreAuthorizedApplicationPermission
    from ._models_py3 import RequiredResourceAccess
    from ._models_py3 import ResourceAccess
    from ._models_py3 import ServicePrincipal
    from ._models_py3 import ServicePrincipalBase
    from ._models_py3 import ServicePrincipalCreateParameters
    from ._models_py3 import ServicePrincipalListResult
    from ._models_py3 import ServicePrincipalObjectResult
    from ._models_py3 import ServicePrincipalUpdateParameters
    from ._models_py3 import SignInName
    from ._models_py3 import User
    from ._models_py3 import UserBase
    from ._models_py3 import UserCreateParameters
    from ._models_py3 import UserGetMemberGroupsParameters
    from ._models_py3 import UserGetMemberGroupsResult
    from ._models_py3 import UserListResult
    from ._models_py3 import UserUpdateParameters
except (SyntaxError, ImportError):
    from ._models import ADGroup  # type: ignore
    from ._models import AddOwnerParameters  # type: ignore
    from ._models import AppRole  # type: ignore
    from ._models import Application  # type: ignore
    from ._models import ApplicationBase  # type: ignore
    from ._models import ApplicationCreateParameters  # type: ignore
    from ._models import ApplicationListResult  # type: ignore
    from ._models import ApplicationUpdateParameters  # type: ignore
    from ._models import CheckGroupMembershipParameters  # type: ignore
    from ._models import CheckGroupMembershipResult  # type: ignore
    from ._models import DirectoryObject  # type: ignore
    from ._models import DirectoryObjectListResult  # type: ignore
    from ._models import Domain  # type: ignore
    from ._models import DomainListResult  # type: ignore
    from ._models import GetObjectsParameters  # type: ignore
    from ._models import GraphError  # type: ignore
    from ._models import GroupAddMemberParameters  # type: ignore
    from ._models import GroupCreateParameters  # type: ignore
    from ._models import GroupGetMemberGroupsParameters  # type: ignore
    from ._models import GroupGetMemberGroupsResult  # type: ignore
    from ._models import GroupListResult  # type: ignore
    from ._models import InformationalUrl  # type: ignore
    from ._models import KeyCredential  # type: ignore
    from ._models import KeyCredentialListResult  # type: ignore
    from ._models import KeyCredentialsUpdateParameters  # type: ignore
    from ._models import OAuth2Permission  # type: ignore
    from ._models import OAuth2PermissionGrant  # type: ignore
    from ._models import OAuth2PermissionGrantListResult  # type: ignore
    from ._models import OptionalClaim  # type: ignore
    from ._models import OptionalClaims  # type: ignore
    from ._models import PasswordCredential  # type: ignore
    from ._models import PasswordCredentialListResult  # type: ignore
    from ._models import PasswordCredentialsUpdateParameters  # type: ignore
    from ._models import PasswordProfile  # type: ignore
    from ._models import PreAuthorizedApplication  # type: ignore
    from ._models import PreAuthorizedApplicationExtension  # type: ignore
    from ._models import PreAuthorizedApplicationPermission  # type: ignore
    from ._models import RequiredResourceAccess  # type: ignore
    from ._models import ResourceAccess  # type: ignore
    from ._models import ServicePrincipal  # type: ignore
    from ._models import ServicePrincipalBase  # type: ignore
    from ._models import ServicePrincipalCreateParameters  # type: ignore
    from ._models import ServicePrincipalListResult  # type: ignore
    from ._models import ServicePrincipalObjectResult  # type: ignore
    from ._models import ServicePrincipalUpdateParameters  # type: ignore
    from ._models import SignInName  # type: ignore
    from ._models import User  # type: ignore
    from ._models import UserBase  # type: ignore
    from ._models import UserCreateParameters  # type: ignore
    from ._models import UserGetMemberGroupsParameters  # type: ignore
    from ._models import UserGetMemberGroupsResult  # type: ignore
    from ._models import UserListResult  # type: ignore
    from ._models import UserUpdateParameters  # type: ignore

from ._graph_rbac_management_client_enums import (
    ConsentType,
    GroupMembershipClaimTypes,
    UserType,
)

__all__ = [
    'ADGroup',
    'AddOwnerParameters',
    'AppRole',
    'Application',
    'ApplicationBase',
    'ApplicationCreateParameters',
    'ApplicationListResult',
    'ApplicationUpdateParameters',
    'CheckGroupMembershipParameters',
    'CheckGroupMembershipResult',
    'DirectoryObject',
    'DirectoryObjectListResult',
    'Domain',
    'DomainListResult',
    'GetObjectsParameters',
    'GraphError',
    'GroupAddMemberParameters',
    'GroupCreateParameters',
    'GroupGetMemberGroupsParameters',
    'GroupGetMemberGroupsResult',
    'GroupListResult',
    'InformationalUrl',
    'KeyCredential',
    'KeyCredentialListResult',
    'KeyCredentialsUpdateParameters',
    'OAuth2Permission',
    'OAuth2PermissionGrant',
    'OAuth2PermissionGrantListResult',
    'OptionalClaim',
    'OptionalClaims',
    'PasswordCredential',
    'PasswordCredentialListResult',
    'PasswordCredentialsUpdateParameters',
    'PasswordProfile',
    'PreAuthorizedApplication',
    'PreAuthorizedApplicationExtension',
    'PreAuthorizedApplicationPermission',
    'RequiredResourceAccess',
    'ResourceAccess',
    'ServicePrincipal',
    'ServicePrincipalBase',
    'ServicePrincipalCreateParameters',
    'ServicePrincipalListResult',
    'ServicePrincipalObjectResult',
    'ServicePrincipalUpdateParameters',
    'SignInName',
    'User',
    'UserBase',
    'UserCreateParameters',
    'UserGetMemberGroupsParameters',
    'UserGetMemberGroupsResult',
    'UserListResult',
    'UserUpdateParameters',
    'ConsentType',
    'GroupMembershipClaimTypes',
    'UserType',
]
