# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum

class ConsentType(str, Enum):
    """Indicates if consent was provided by the administrator (on behalf of the organization) or by an
    individual.
    """

    all_principals = "AllPrincipals"
    principal = "Principal"

class GroupMembershipClaimTypes(str, Enum):
    """Configures the groups claim issued in a user or OAuth 2.0 access token that the app expects.
    """

    none = "None"
    security_group = "SecurityGroup"
    all = "All"

class UserType(str, Enum):
    """A string value that can be used to classify user types in your directory, such as 'Member' and
    'Guest'.
    """

    member = "Member"
    guest = "Guest"
